image: python:3.5

all_tests:
  script:
   - pip install -r requirements.txt
   - python manage.py collectstatic --noinput --pythonpath lib
   - python3 manage.py test -k
  when: on_success


staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-python-test-staging --key=$HEROKU_STAGING_API_KEY
  only:
  - master