# Generated by Django 2.1.5 on 2019-02-13 16:19

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('apartment_age', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('monthly_cost', models.PositiveIntegerField()),
                ('vote_amount', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('profile_picture', imagekit.models.fields.ProcessedImageField(upload_to='apartments/')),
            ],
        ),
    ]
