# Generated by Django 2.1.5 on 2019-03-29 22:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
    ]
