# Generated by Django 2.1.5 on 2019-03-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image1',
        ),
    ]
