# Generated by Django 2.1.5 on 2019-03-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='review_made',
        ),
    ]
