# Generated by Django 2.1.5 on 2019-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_remove_contract_review_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='review_made',
            field=models.BooleanField(default=False),
        ),
    ]
