# Generated by Django 2.1.5 on 2019-02-17 10:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_auto_20190217_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='apartments/'),
        ),
    ]
