# Generated by Django 2.1.5 on 2019-02-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_phone_number'),
        ('apartments', '0011_auto_20190217_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_text', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='periods',
            field=models.ManyToManyField(to='apartments.Contract'),
        ),
    ]
