# Generated by Django 2.1.5 on 2019-02-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_auto_20190217_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='periods',
            new_name='contracts',
        ),
    ]
