# Generated by Django 2.1.5 on 2019-02-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_phone_number'),
        ('apartments', '0013_auto_20190217_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contract_owner', to='authentication.Profile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='subtenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contract_subtenant', to='authentication.Profile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tenant', to='authentication.Profile'),
        ),
    ]
