# Generated by Django 2.1.5 on 2019-02-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_auto_20190227_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='authentication.Profile'),
        ),
    ]
