# Generated by Django 2.1.5 on 2019-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_auto_20190227_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='pending',
            field=models.BooleanField(),
        ),
    ]
