# Generated by Django 2.1.5 on 2019-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_auto_20190228_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
