# Generated by Django 2.1.5 on 2019-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0023_apartment_original_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='owner_approved',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='original_owner',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
