# Generated by Django 2.1.5 on 2019-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0024_auto_20190304_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='owner_approved',
            field=models.BooleanField(null=True),
        ),
    ]
