# Generated by Django 2.1.5 on 2019-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0025_auto_20190304_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='owner_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
