# Generated by Django 2.1.5 on 2019-03-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0026_auto_20190304_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='owner_approved',
        ),
    ]
