# Generated by Django 2.1.5 on 2019-03-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0028_contract_owner_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='owner_approved',
        ),
    ]
