# Generated by Django 2.1.5 on 2019-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0030_contract_owner_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='owner_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
