# Generated by Django 2.1.5 on 2019-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0031_auto_20190306_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='craxy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
