# Generated by Django 2.1.5 on 2019-03-07 12:45

from django.db import migrations
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0032_contract_craxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='craxy',
        ),
        migrations.AddField(
            model_name='contract',
            name='tenants',
            field=multi_email_field.fields.MultiEmailField(blank=True, null=True),
        ),
    ]
