# Generated by Django 2.1.5 on 2019-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0033_auto_20190307_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
