# Generated by Django 2.1.5 on 2019-03-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0034_auto_20190312_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='apartments.Contract'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='original_owner',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
