# Generated by Django 2.1.5 on 2019-03-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0034_auto_20190312_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='apartment_age',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='apartments.Contract'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='latitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='original_owner',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
