# Generated by Django 2.1.5 on 2019-03-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0035_auto_20190315_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(null=True, upload_to='img')),
                ('image_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
            ],
        ),
    ]
