# Generated by Django 2.1.5 on 2019-03-20 22:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0036_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='mainimage',
            field=imagekit.models.fields.ProcessedImageField(upload_to='apartments/'),
        ),
    ]
