# Generated by Django 2.1.5 on 2019-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0037_auto_20190320_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='image_for',
        ),
        migrations.RemoveField(
            model_name='apartmentimage',
            name='mainimage',
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='contract_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
