# Generated by Django 2.1.5 on 2019-03-20 22:34

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0038_auto_20190320_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='contract_text',
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='image_for',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='mainimage',
            field=imagekit.models.fields.ProcessedImageField(default=10, upload_to='apartments/'),
            preserve_default=False,
        ),
    ]
