# Generated by Django 2.1.5 on 2019-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0039_auto_20190320_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentimage',
            old_name='mainimage',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='apartmentimage',
            name='image_for',
        ),
        migrations.AddField(
            model_name='apartment',
            name='images',
            field=models.ManyToManyField(to='apartments.ApartmentImage'),
        ),
    ]
