# Generated by Django 2.1.5 on 2019-03-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0041_auto_20190321_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment'),
        ),
    ]
