# Generated by Django 2.1.5 on 2019-02-14 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='vote_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
