# Generated by Django 2.1.5 on 2019-02-14 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20190214_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
