# Generated by Django 2.1.5 on 2019-02-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20190214_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='profile_picture',
            new_name='image1',
        ),
    ]
