# Generated by Django 2.1.5 on 2019-02-14 12:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20190214_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='apartments/'),
        ),
    ]
