# Generated by Django 2.1.5 on 2019-02-17 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20190214_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
