# Generated by Django 2.1.5 on 2019-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_auto_20190217_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='periods',
            field=models.ManyToManyField(to='apartments.Period'),
        ),
    ]
