# Generated by Django 2.1.5 on 2019-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_date',
            field=models.DateField(null=True),
        ),
    ]
