# Generated by Django 2.1.5 on 2019-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(default=47244448),
            preserve_default=False,
        ),
    ]
