# Generated by Django 2.1.5 on 2019-03-18 13:45

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='profile_picture',
        #     field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='apartments/'),
        # ),
    ]
