# Generated by Django 2.1.5 on 2019-03-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_is_admin'),
        ('authentication', '0003_profile_profile_picture'),
    ]

    operations = [
    ]
