AWS_UPLOAD_BUCKET = "sharebb"

AWS_UPLOAD_USERNAME = "markusva"

AWS_UPLOAD_GROUP = "sharebb_group"

AWS_UPLOAD_REGION = 'eu-north-1'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAJTN3MPFZWBPXUGCQ"

AWS_UPLOAD_SECRET_KEY = "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"